# Generated by Django 3.0.8 on 2020-12-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reviews',
        ),
        migrations.AddField(
            model_name='item',
            name='reviews',
            field=models.ManyToManyField(to='interface.Review'),
        ),
    ]
