# Generated by Django 3.1.2 on 2021-01-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20201214_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_positive',
            field=models.BooleanField(),
        ),
    ]
