# Generated by Django 3.1.2 on 2021-01-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_review_is_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
