# Generated by Django 3.1.2 on 2021-01-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_auto_20210122_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='occurrences',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
